import Header from './Header';
import Head from 'next/head';
import Footer from './Footer';

export default function Layout({children}) {
  return (
    <div>
      <Header />
      <Head>
        <title>Wall App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {children}
      <Footer />
    </div>
  );
}
